### ISSUE TITLE
Support std interfaces in naming rules

### ISSUE THREAD

**Issue by igoramorim** [arch-go/arch-go#87]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/arch-go/arch-go/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/arch-go/arch-go/blob/main/CONTRIBUTING.md)."
- [X] I have discussed this feature request with the community.

### Describe the background of your feature request

It is not possible to validate that a struct implements an interface from the Go std packages.

### Describe your idea

That would be nice to have some way of validating that a struct implements an interface from the Go std packages, such as `error`:

```go
type MyCustomErr struct {
  ...
}

func (e *MyCustomErr) Error() string {
  ...
}
```

```yaml
namingRules:
  - package: "**.internal.**"
    interfaceImplementationNamingRule:
      structsThatImplement: "error"
      shouldHaveSimpleNameEndingWith: "Err"
```

or

```yaml
namingRules:
  - package: "**.internal.**"
    interfaceImplementationNamingRule:
      structsThatImplement:
        external: "error"
      shouldHaveSimpleNameEndingWith: "Err"
```

### Are there any workarounds or alternatives?

No.

### Version

arch-go version 1.5.4
