### ISSUE TITLE
More flexibility in package pattern names

### ISSUE THREAD

**Issue by igoramorim** [arch-go/arch-go#88]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/arch-go/arch-go/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/arch-go/arch-go/blob/main/CONTRIBUTING.md)."
- [X] I have discussed this feature request with the community.

### Describe the background of your feature request

Lets say I have this structure of packages:

```
domain
|_ usa
|_ usared
|_ bra
|_ bragreen
```

And I want to validate that:
- `usa` and `usared` should not depends on `bra`, `bragreen`
- `bra` and `bragreen` should not depends on `usa`, `usared`

For this I have to write:

```yaml
dependenciesRules:
  - package: "**.usa.**"
    shouldNotDependsOn:
      internal:
        - "**.bra.**"
        - "**.bragreen**"
 - package: "**.usared.**"
  shouldNotDependsOn:
    internal:
      - "**.bra.**"
      - "**.bragreen**"
 - package: "**.bra.**"
  shouldNotDependsOn:
    internal:
      - "**.usa.**"
      - "**.usared**"
 - package: "**.bragreen.**"
  shouldNotDependsOn:
    internal:
      - "**.usa.**"
      - "**.usared**"
```

It is a little repetitive and if I create more packages, like `col` and `colblue`, I would have to update every existing rule.

### Describe your idea

That would be nice to have more flexibility using the package naming patterns, like some way of matching an specific prefix or suffix of a word. For example:

```yaml
dependenciesRules:
  - package: "**.usa*.**" # 1
    shouldNotDependsOn:
      internal:
        - "**.^usa.**" # 2
 - package: "**.bra*.**"
  shouldNotDependsOn:
    internal:
      - "**.^bra.**"
```

1 - Added '*' after 'usa' to say that every package name that has a prefix 'usa' should be included in the rule, like `usared`
2 - Added '^' before 'usa' to say that should not depends on packages that does not has the prefix 'usa'

Of course the use of '*' and '^' are just ideas.

### Are there any workarounds or alternatives?

No.

### Version

arch-go version 1.5.4
